# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 073b477657246d8a8c292091b8f799b4e13b412502088891559e72978c549705e1ce5d15307c665f73c4469f11b832c30eddeac098ae2bb87a677671a8368382

test:
  secret_key_base: 990a326d235257817c2209ee166d915599ccd429feb613db40ab6ef7f2a6c97c835830f1e3ba3d0b866267bde89095e1229d8dc1440904581ed8fe89bf82a2e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
